-- MySQL Script generated by MySQL Workbench
-- Tue Apr 19 15:08:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema utleie
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema utleie
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `utleie` DEFAULT CHARACTER SET utf8 ;
USE `utleie` ;

-- -----------------------------------------------------
-- Table `utleie`.`Komponenter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utleie`.`Komponenter` (
  `Komponent ID` INT NOT NULL AUTO_INCREMENT,
  `Navn` VARCHAR(45) NULL,
  `Beholdning` INT NULL,
  PRIMARY KEY (`Komponent ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `utleie`.`Låner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utleie`.`Låner` (
  `Låner ID` INT NOT NULL AUTO_INCREMENT,
  `Navn` VARCHAR(45) NULL,
  `Utlånsdato` DATE NULL,
  `Leveringsfrist` DATE NULL,
  `E-post` VARCHAR(45) NULL,
  `Mobilnummer` INT NULL,
  PRIMARY KEY (`Låner ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `utleie`.`Lån`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utleie`.`Lån` (
  `idLån` INT NOT NULL AUTO_INCREMENT,
  `Komponenter_Komponent ID` INT NOT NULL,
  `Låner_Låner ID` INT NOT NULL,
  PRIMARY KEY (`idLån`, `Komponenter_Komponent ID`, `Låner_Låner ID`),
  INDEX `fk_Lån_Komponenter_idx` (`Komponenter_Komponent ID` ASC) VISIBLE,
  INDEX `fk_Lån_Låner1_idx` (`Låner_Låner ID` ASC) VISIBLE,
  CONSTRAINT `fk_Lån_Komponenter`
    FOREIGN KEY (`Komponenter_Komponent ID`)
    REFERENCES `utleie`.`Komponenter` (`Komponent ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lån_Låner1`
    FOREIGN KEY (`Låner_Låner ID`)
    REFERENCES `utleie`.`Låner` (`Låner ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
